from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from database import DatabaseManager
from dotenv import load_dotenv
from config import SQL_GENERATION_PROMPT, SQL_CORRECTION_PROMPT
load_dotenv()

#======================================
#SQLGeneratorChain class
#======================================
class SQLGeneratorChain:
    def __init__(self, model_name: str = "llama-3.3-70b-versatile"):
        # Initialize LangChain's Groq wrapper with zero temperature for deterministic outputs/No creative output
        self.llm = ChatGroq(
            model=model_name,
            temperature=0.0,
        )

    #======================================
    #Function to clean the SQL Query
    #======================================
    def clean_sql_query_output(self, raw_sql: str) -> str:
        # Strips markdown code block formatting (```sql ... ```) if generated by LLM
        cleaned = raw_sql.strip()
        if cleaned.startswith("```"):
            lines = cleaned.splitlines()
            lines = [l for l in lines if not l.startswith("```")]
            cleaned = "\n".join(lines).strip()
        return cleaned

    #======================================
    #Function to generate query first time
    #======================================
    def generate_sql_query(self, user_question: str, schema: str) -> str:
        # Generates initial PostgreSQL query from natural language user input
        prompt = ChatPromptTemplate.from_messages([
            ("system", SQL_GENERATION_PROMPT),
            ("human", "{question}")
        ])
        chain = prompt | self.llm
        response = chain.invoke({"schema": schema, "question": user_question})
        return self.clean_sql_query_output(str(response.content))


    #======================================
    #Function to call llm if They wrote wrong query previously
    #======================================
    def correct_the_sql_query(self, failed_query: str, error_message: str, schema: str) -> str:
        # Feeds database error message back to Groq to fix broken query
        prompt = ChatPromptTemplate.from_messages([
            ("system", SQL_CORRECTION_PROMPT)
        ])
        chain = prompt | self.llm
        response = chain.invoke({
            "schema": schema,
            "failed_query": failed_query,
            "error_message": error_message
        })
        return self.clean_sql_query_output(str(response.content))

    #======================================
    #Function which Running in loop upto max_retrie if Query failed to fetch the data from databse
    #======================================
    def run_with_self_correction(self, user_question: str, db_manager: DatabaseManager, max_retries: int = 3):
        """
        # Pipeline execution:
        """
        schema = db_manager.get_schema()
        attempts_log = []
        
        # First Attempt Generation
        current_query = self.generate_sql_query(user_question, schema)
        
        # Retry execution loop
        for attempt in range(1, max_retries + 1):
            try:
                # Attempt executing SQL on Neon DB
                df = db_manager.execute_query(current_query)
                attempts_log.append({
                    "attempt": attempt,
                    "query": current_query,
                    "status": "SUCCESS"
                })
                return df, current_query, attempts_log

            except Exception as error:
                
                error_msg = str(error)
                attempts_log.append({
                    "attempt": attempt,
                    "query": current_query,
                    "status": "FAILED",
                    "error": error_msg
                })

                # Stop loop if maximum retries reached
                if attempt == max_retries:
                    break

                # Trigger self-correction LLM call
                current_query = self.correct_the_sql_query(
                    failed_query=current_query,
                    error_message=error_msg,
                    schema=schema
                )

        raise RuntimeError(f"Could not generate valid PostgreSQL query after {max_retries} attempts.")